language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"
  
# command to install dependencies
install:
  - pip install oyaml flask
  
# command to run tests
script:
  - sh test.sh
